---
before_script:
- gem install hoe kpeg racc --no-rdoc --no-ri
- gem install minitest -v '~> 4.0'
language: ruby
notifications:
  email:
  - mail@zzak.io
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
- 2.1.0
- 2.2.0
- ruby-head
- rbx-2
script: rake test
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: rbx-2
    - rvm: ruby-head
