---
before_install:
  - gem install bundler --no-document
language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - jruby-9.1.15.0
env:
  global:
    NOBENCHMARK=1
script: bundle exec rake
