---
before_script:
- gem install bundler --no-document
language: ruby
notifications:
  email:
  - mail@zzak.io
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
- 2.1.0
- 2.2.0
- ruby-head
- rbx-2
script: rake
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: rbx-2
    - rvm: ruby-head
