---
before_install:
  - gem install bundler --no-document
language: ruby
notifications:
  email:
  - mail@zzak.io
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby-9.1.13.0
env:
  global:
    NOBENCHMARK=1
script: rake
matrix:
  allow_failures:
    - rvm: jruby-9.1.13.0
