---
before_install:
  - gem install bundler --no-document
language: ruby
notifications:
  email:
  - mail@zzak.io
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - rbx-2
  - jruby-1.7.26
  - jruby-9.1.9.0
env:
  global:
    NOBENCHMARK=1
script: rake
matrix:
  allow_failures:
    - rvm: jruby-1.7.26
    - rvm: jruby-9.1.9.0
    - rvm: rbx-2
